Cross-platform safe temp file
opendp/dp-wizard pull request #146
Opened 2024-11-05 20:59 UTC by mccalluc

- Fix #141 
- On the good side, this is more likely to work on Windows
- On the bad side, a new temp directory is created on every run
  - We could clean it up in the `session.on_ended` handler, but I'm not sure the complexity is worth it?

time: ~1 hour, mostly thinking about different options.

2024-11-07 18:28 UTC, ekraffmiller commented
As another option, could we use [gettempdir()](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir)?  It supports different environments.  
Or, can we create demo.csv just once and include it in the application?

2024-11-07 18:56 UTC, mccalluc commented
Good call!

2024-11-07 19:38 UTC, ekraffmiller requested changes
See comment about using a temp dir

2024-11-07 19:53 UTC, mccalluc commented
It looks like that is still doesn't return something as simple as `/tmp`:
```
>>> from tempfile import gettempdir
>>> gettempdir()
'/var/folders/jm/40wztt291610f8pk5w0sw20r0000gq/T'
```
I'd prefer to keep the status quo: I think it's nice to have a directory that is just for this application, rather than sharing one that could inadvertently interfere with other applications.

2024-11-07 20:00 UTC, mccalluc commented
Second, or third thought: Would be good to try checking in the generated file. One the fence, but it would mitigate this whole temp directory problem.

2024-11-19 19:35 UTC, mccalluc commented
- Close in favor of #167

2024-11-19 19:35 UTC, closed without merging